<?php

declare(strict_types=1);

namespace Webactueel\Translate\Automation;

use Webactueel\Translate\Database\Tables;
use Webactueel\Translate\Frontend\LanguageDetector;
use Webactueel\Translate\Support\Input;
use Webactueel\Translate\Translation\TranslationRepository;

if (! defined('ABSPATH')) {
    exit;
}

// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching -- Plugin-owned tables.
// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Table identifiers are generated by plugin-owned helpers.

final class ContentChangeWatcher
{
    public function register(): void
    {
        add_action('save_post', [$this, 'handle_post_save'], 20, 3);
        add_action('edited_term', [$this, 'handle_term_save'], 20, 3);
    }

    public function handle_post_save(int $postId, \WP_Post $post, bool $update): void
    {
        if (! $update || wp_is_post_revision($postId) || wp_is_post_autosave($postId)) {
            return;
        }
        if ($post->post_status !== 'publish' || ! is_post_type_viewable($post->post_type)) {
            return;
        }

        $repo = new TranslationRepository();
        $repo->upsert_string((string) $post->post_title, $post->post_type, $postId, 'post_title', 'post:' . $postId . ':title');
        $repo->upsert_string((string) $post->post_excerpt, $post->post_type, $postId, 'post_excerpt', 'post:' . $postId . ':excerpt');
        foreach ($this->split_text(wp_strip_all_tags(strip_shortcodes((string) $post->post_content))) as $index => $part) {
            $repo->upsert_string($part, $post->post_type, $postId, 'post_content', 'post:' . $postId . ':content:auto:' . $index);
        }
        $this->upsert_seo_fields($repo, $postId);
        $this->mark_source_outdated($post->post_type, $postId);
    }

    /**
     * Re-queue the active SEO plugin's title/description when a post is saved.
     *
     * SEO plugins persist their meta during the same save_post request, so reading the
     * fields here captures editor changes and keeps the SEO translation queue current.
     */
    private function upsert_seo_fields(TranslationRepository $repo, int $postId): void
    {
        if (! \Webactueel\Translate\Seo\SeoFieldExtractor::is_available()) {
            return;
        }
        foreach (\Webactueel\Translate\Seo\SeoFieldExtractor::read_fields($postId) as $field => $value) {
            $clean = trim(wp_strip_all_tags($value));
            if ($clean === '') {
                continue;
            }
            $repo->upsert_string(
                $clean,
                \Webactueel\Translate\Seo\SeoFieldExtractor::SOURCE_TYPE,
                $postId,
                \Webactueel\Translate\Seo\SeoFieldExtractor::context($field),
                \Webactueel\Translate\Seo\SeoFieldExtractor::source_key($field)
            );
        }
    }

    public function handle_term_save(int $termId, int $ttId, string $taxonomy): void
    {
        $term = get_term($termId, $taxonomy);
        if (! $term || is_wp_error($term)) {
            return;
        }
        $repo = new TranslationRepository();
        $repo->upsert_string((string) $term->name, 'term', $termId, 'term_name', 'term:' . $taxonomy . ':' . $termId . ':name');
        $repo->upsert_string((string) $term->description, 'term', $termId, 'term_description', 'term:' . $taxonomy . ':' . $termId . ':description');
        $this->mark_source_outdated('term', $termId);
    }

    private function mark_source_outdated(string $sourceType, int $sourceId): void
    {
        global $wpdb;
        $sourceType = sanitize_key($sourceType);
        $sourceId = absint($sourceId);
        if ($sourceType === '' || $sourceId <= 0) {
            return;
        }
        $strings = Tables::sql_identifier(Tables::strings());
        $translations = Tables::sql_identifier(Tables::translations());
        $languages = array_filter(array_map(static function (array $language): string {
            return ! empty($language['is_default']) ? '' : Input::key($language['code'] ?? '');
        }, LanguageDetector::active_languages()));
        if ($languages === []) {
            return;
        }
        $placeholders = implode(',', array_fill(0, count($languages), '%s'));
        $params = array_merge(['outdated', current_time('mysql'), $sourceType, $sourceId], array_values($languages));
        $wpdb->query($wpdb->prepare(
            "UPDATE `{$translations}` t INNER JOIN `{$strings}` s ON s.id = t.string_id SET t.status = %s, t.updated_at = %s WHERE s.source_type = %s AND s.source_id = %d AND t.language_code IN ({$placeholders}) AND t.status IN ('published','reviewed','needs_review','draft')",
            ...$params
        ));
    }

    /** @return list<string> */
    private function split_text(string $text): array
    {
        $text = preg_replace('/\s+/u', ' ', trim($text));
        if (! is_string($text) || $text === '') {
            return [];
        }
        $parts = preg_split('/(?<=[.!?])\s+/u', $text) ?: [];
        return array_values(array_filter(array_map(static function (string $part): string {
            return trim($part);
        }, $parts), static function (string $part): bool {
            return $part !== '' && (function_exists('mb_strlen') ? mb_strlen($part) >= 3 : strlen($part) >= 3);
        }));
    }
}
